#index:
#    path: /
#    controller: App\Controller\DefaultController::index

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

rest_api_v1:
    resource: ../src/Controller/Rest/v1/
    type: annotation
    prefix: /api/v1
auth:
    resource: 'App\Controller\AuthController'
    type: annotation
tag:
    resource: 'App\Controller\TagController'
    type: annotation
tag_no_page:
    resource: 'App\Controller\TagController'
    type: annotation
index:
    resource: 'App\Controller\HomeController'
    type: annotation
category:
    resource: 'App\Controller\CategoryController'
    type: annotation
user:
    resource: 'App\Controller\UserController'
    type: annotation
blog:
    resource: 'App\Controller\BlogController'
    type: annotation
contact:
    resource: 'App\Controller\ContactController'
    type: annotation
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin
blog_post:
    resource: 'App\Controller\BlogPostController'
    type: annotation
#blog_route:
#    resource: .
#    type: blog_route